<?php if( 1 == Mage::getStoreConfig('contatoProdDisponivel_options/general/enabled') ): ?>	
	<?php $_product = $this->getProduct();?>
	<div class="contato-sobreproduto-form">
		<h1>Faça uma pergunta sobre o Produto</h1>
		<form action="" method="post" onsubmit="return false;">
			<p>
				<label for="nome"><?php echo $this->__('Name'); ?></label>
				<input id="nome" type="text" name="nome" value="" />
			</p>
			<p>
				<label for="email"><?php echo $this->__('Email'); ?></label>
				<input id="email" type="text" name="email" value="" />
			</p>
			<p>
				<label for="telefone"><?php echo $this->__('Telephone'); ?></label>
				<input type="text" name="telefone" id="telefone" value="" />
			</p>
			<p>
				<label><?php echo $this->__('Message'); ?> </label>
				<textarea name="mensagem" id="mensagem" value=""></textarea>
			</p>
			<p><button type="submit" onclick="QuestionAboutProduct();"><?php echo $this->__('Submit'); ?></button></p>	
		</form>
		<div id="carregando"></div>
	</div>
	
	<script type="text/javascript">
	//<![CDATA[
		function QuestionAboutProduct()
		{
			urlAjax = '<?php echo Mage::getBaseUrl().'contato/produto'; ?>';
			new Ajax.Request(
				urlAjax,
				{ method: 'POST',
					parameters: {
						nome: 	  $('nome').value,
						produto:  '<?php echo $_product->getName(); ?>',
						email: 	  $('email').value,
						telefone: $('telefone').value,
						mensagem: $('mensagem').value,
					},
					evalScripts: true,
					onLoading: function( transport ){
						$('carregando').update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>" /> <span style="color: #888;"><?php echo $this->__('Loading...') ?></span>');
					},
					onComplete: function( transport ){},
					onSuccess: function( result ){
						if( 200 == result.status ){
							try {
								var res = result.responseText.evalJSON();
								$('carregando').hide();
								alert(res);
							}	
							catch(e){
								alert(e.message);
							}
						}		
					}
				}
			);
		}
	//]]>
	</script>
<?php endif; ?>