<?php if( 1 == Mage::getStoreConfig('contatoProdDisponivel_options/general/enabled') ): ?>	
	<?php $_product = $this->getProduct();?>
	<h1>Preço Sob Consulta </h1>
	<div class="precoConsulta">
	        <label>Deixe seu contato para enviarmos um orçamento</label>
	        
	        <input type="text" id="nome" value="Nome:" onblur="if(this.value==''){ this.value='Nome:' }" onfocus="if(this.value=='Nome:'){this.value=''};" name="nome" class="texto"/>
	        
	        <input type="text" id="email" value="E-mail:" onblur="if(this.value==''){ this.value='E-mail:' }" onfocus="if(this.value=='E-mail:'){this.value=''};" name="email"  class="texto"/>
	        
	        <input type="text" id="telefone" value="Telefone:" onblur="if(this.value==''){ this.value='Telefone:' }" onfocus="if(this.value=='Telefone:'){this.value=''};" name="telefone" class="texto" />
	        
	        <textarea id="mensagem" name="mensagem" onblur="if(this.value==''){ this.value='Mensagem:' }" onfocus="if(this.value=='Mensagem:'){this.value=''};">Mensagem:</textarea>
	        <input type="submit" onclick="QuestionAboutProduct(); return false;" value="ENVIAR DADOS" class="envia" />
	        <div id="carregando"></div>
	</div>
	
	<script type="text/javascript">
	//<![CDATA[
		function QuestionAboutProduct()
		{

			var emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z]+\.[a-zA-Z]+(\.[a-zA-Z]+)?/g;
			var phoneRegex = /^([0-9]){2,3}(.)?[0-9]{4,5}(.)?[0-9]{4}/g;

			var nome     = $('nome');
			var email    = $('email');
			var telefone = $('telefone');
			var mensagem = $('mensagem');

			if( nome.value.trim() == '' || nome.value == 'Nome:' )
			{
				alert('Digite um nome válido');
				return false;
			}
			if( email.value.trim() == '' || email.value == 'E-mail:' || !emailRegex.test( email.value ) )
			{
				alert('Digite um e-mail válido');
				return false;
			}
			if( telefone.value == '' || telefone.value == 'Telefone:' || !phoneRegex.test( telefone.value ) )
			{
				alert('Digite um telefone válido');
				return false;
			}
			if( mensagem.value == '' )
			{
				alert('Digite uma mensagem');
				return false;
			}

			urlAjax = '<?php echo Mage::getBaseUrl().'contato/produto'; ?>';
			new Ajax.Request(
				urlAjax,
				{ method: 'POST',
					parameters: {
						nome: 	  nome.value,
						produto:  '<?php echo $_product->getName(); ?>',
						email: 	  email.value,
						telefone: telefone.value,
						mensagem: mensagem.value,
					},
					evalScripts: true,
					onLoading: function( transport ){
						$('carregando').update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>" /> <span style="color: #888;"><?php echo $this->__('Loading...') ?></span>');
					},
					onComplete: function( transport ){},
					onSuccess: function( result ){
						if( 200 == result.status ){
							try {
								var res = result.responseText.evalJSON();
								$('carregando').hide();
								alert(res);
							}	
							catch(e){
								$('carregando').hide();
								alert(e.message);
							}
						}		
					}
				}
			);
		}
	//]]>
	</script>
<?php endif; ?>